# Generated by Django 5.0.1 on 2024-02-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlahe', '0002_post_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='witersHub/media/blank profile photo.jpeg', upload_to='profile_images'),
        ),
    ]
